name: Renovate

on:
  schedule:
    - cron: '0 * * * *'

  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v2.0.6
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Renovate
        uses: renovatebot/github-action@v42.0.4
        with:
          configurationFile: .github/renovate-config.json
          token: ${{ steps.generate_token.outputs.token }}
        env:
          RENOVATE_PLATFORM_COMMIT: true
